### ISSUE TITLE
Each time I pull the code, the path for libraries has to be reset. Sikander, it looks like we are using absolute paths for libraries.

### ISSUE THREAD

**Issue by shivrajpant** [sikanderkhursheed/SoftwareTestingProject#5]

**Comment by sikanderkhursheed** [comment]
Yeah, we can resolve these issues by adding relative paths for the jar files so that whenever anyone clones the project they can run it without relinking the libraries.

**Comment by shivrajpant** [comment]
I have resolved the problem. Please check it out.

**Comment by sikanderkhursheed** [comment]
Yes, it is resolved and working perfectly.
